version: "3.8"

#sudo chown -R $USER:$USER /caminho/para/pasta/no/host

services:
    # image project
    laravel-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./laravel:/var/www
        networks:
            - laravel

    # nuxt
    node-nuxt:
        image: node:21
        container_name: node-nuxt
        restart: unless-stopped
        ports:
            - '3000:3000'
        working_dir: /var/www
        volumes:
            - ./nuxt:/var/www

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx
        ports:
            # laravel port
            - "8001:80"
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./laravel/public:/var/www/public
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:8.0
        container_name: db
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3301:3306"
        networks:
            - laravel

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
