version: "3.8"

#sudo chown -R $USER:$USER /caminho/para/pasta/no/host

services:
    # image project
    auth-app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./auto-api:/var/www
        networks:
            - laravel

    # nuxt
    auth-nuxt:
        image: node:21
        restart: unless-stopped
        ports:
            - '3000:3000'
        working_dir: /var/www
        volumes:
            - ./x-nuxt2:/var/www

    # nginx
    auth-nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            # laravel port
            - "8001:80"
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
            - ./auto-api/public:/var/www/public
        networks:
            - laravel

    # db mysql
    auth-db:
        image: mysql:8.0
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3301:3306"
        networks:
            - laravel

    # PHPMyAdmin
    auth-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            PMA_HOST: auth-db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
